# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0004_auto_20160916_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to='students/static/photos'),
        ),
    ]
